<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3671" started-at="2020-03-27T05:44:18Z" finished-at="2020-03-27T05:44:21Z">
    <groups>
    </groups>
    <test name="Test slider" duration-ms="3671" started-at="2020-03-27T05:44:18Z" finished-at="2020-03-27T05:44:21Z">
      <class name="tests.SliderTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:tests.SliderTest@5b275dab]" name="beforeTest" is-config="true" duration-ms="1851" started-at="2020-03-27T07:44:18Z" finished-at="2020-03-27T07:44:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Test slider]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="testSlider()[pri:0, instance:tests.SliderTest@5b275dab]" name="testSlider" duration-ms="1802" started-at="2020-03-27T07:44:20Z" finished-at="2020-03-27T07:44:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1] but found [1.5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1] but found [1.5]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at tests.SliderTest.testSlider(SliderTest.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSlider -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.SliderTest@5b275dab]" name="closeBrowser" is-config="true" duration-ms="0" started-at="2020-03-27T07:44:21Z" finished-at="2020-03-27T07:44:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.SliderTest -->
    </test> <!-- Test slider -->
  </suite> <!-- Suite -->
</testng-results>
